let express = require("express")
let app = express()
const cors = require("cors")
const router = require("./router/auth")
const mongoose = require("./db/models/connection")
const bodyParser = require("body-parser")
const product = require("./router/product")
const order = require("./router/Order")
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
app.use(cors())
app.use("/auth", router)
app.use("/food", product)
app.use("/order",order)